services:
  mysql:
    image: mysql:8.0
    container_name: foodordering-mysql
    environment:
      MYSQL_ROOT_PASSWORD: Root@123
      MYSQL_DATABASE: foodorderingdb
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
    ports:
      - "3306:3306"

  tomcat:
    build: .
    container_name: foodordering-tomcat
    depends_on:
      - mysql
    ports:
      - "10000:10000"